amqphub:
  amqp10jms:
    username: admin
    password: password
    remote-url: amqps://localhost:61617?transport.trustStoreLocation=target/classes/truststore.p12&transport.trustStorePassword=changeit&transport.verifyHost=false
    #failover:(amqps://localhost:61617,amqps://localhost:61717)?transport.trustStoreLocation=truststore.p12&transport.trustStorePassword=changeit&amqp.idleTimeout=10000&jms.requestTimeout=10000&jms.sendTimeout=10000&failover.randomize=true&failover.reconnectDelay=1000&failover.useReconnectBackOff=false
    pool.enabled: true
    pool.maxConnections: 1
    pool.maxSessionsPerConnection: 500

spring:
  jms:
    template:
      session:
        acknowledge-mode: client
    listener:
      min-concurrency: 1
      max-concurrency: 10
      session:
        acknowledge-mode: client

logging:
  # file:
  #   path: logs
  level:
    root: info
    # org.apache.qpid.jms: debug
    # org.apache.qpid.jms.provider.failover.FailoverProvider: debug
    # org.messaginghub.pooled.jms: debug